export const SCRCPY_CAPABILITIES = {
  version: "4.0",
  integration: "cloud-phone",
  network: {
    description:
      "Official scrcpy pushes scrcpy-server.jar to the device, opens adb reverse/forward tunnels, streams H264/video and control over local sockets. ws-scrcpy bridges those sockets to browser WebSockets for web playback.",
    officialFlow: ["adb push server jar", "adb reverse/forward", "video socket", "control socket"],
    wsScrcpyFlow: ["Node proxy", "WebSocket", "browser decoder (MSE/Broadway/WebCodecs)"],
  },
  categories: [
    {
      id: "connection",
      name: "连接 / Connection",
      options: [
        { flag: "serial", type: "string", description: "ADB 设备序列号" },
        { flag: "tcpip", type: "string", description: "连接 TCP/IP 设备 (host:port)" },
        { flag: "select-usb", type: "boolean", description: "选择 USB 设备" },
        { flag: "select-tcpip", type: "boolean", description: "选择 TCP/IP 设备" },
        { flag: "force-adb-forward", type: "boolean", description: "强制 adb forward 模式" },
        { flag: "tunnel-host", type: "string", description: "隧道主机" },
        { flag: "tunnel-port", type: "number", description: "隧道端口" },
        { flag: "port", type: "range", description: "端口范围 (first:last)" },
        { flag: "kill-adb-on-close", type: "boolean", description: "关闭时结束 adb 服务" },
      ],
    },
    {
      id: "video",
      name: "视频 / Video",
      options: [
        { flag: "max-size", alias: "m", type: "number", description: "最大边长" },
        { flag: "video-bit-rate", alias: "b", type: "number", description: "视频码率" },
        { flag: "max-fps", type: "number", description: "最大帧率" },
        { flag: "video-codec", type: "enum", values: ["h264", "h265", "av1"], description: "视频编码" },
        { flag: "video-encoder", type: "string", description: "指定视频编码器" },
        { flag: "video-codec-options", type: "string", description: "编码器额外参数" },
        { flag: "crop", type: "string", description: "裁剪区域" },
        { flag: "angle", type: "number", description: "旋转角度" },
        { flag: "display-id", type: "number", description: "显示器 ID" },
        { flag: "video-source", type: "enum", values: ["display", "camera"], description: "视频源" },
        { flag: "capture-orientation", type: "string", description: "采集方向" },
        { flag: "display-orientation", type: "string", description: "显示方向" },
        { flag: "no-video", type: "boolean", description: "禁用视频" },
        { flag: "no-video-playback", type: "boolean", description: "不解码播放视频" },
        { flag: "no-downsize-on-error", type: "boolean", description: "编码失败时不自动降分辨率" },
        { flag: "print-fps", type: "boolean", description: "打印 FPS" },
      ],
    },
    {
      id: "audio",
      name: "音频 / Audio",
      options: [
        { flag: "no-audio", type: "boolean", description: "禁用音频" },
        { flag: "audio-bit-rate", type: "number", description: "音频码率" },
        { flag: "audio-codec", type: "enum", values: ["opus", "aac", "flac", "raw"], description: "音频编码" },
        { flag: "audio-encoder", type: "string", description: "音频编码器" },
        { flag: "audio-codec-options", type: "string", description: "音频编码器参数" },
        { flag: "audio-source", type: "string", description: "音频源 (output/mic/playback/...)" },
        { flag: "require-audio", type: "boolean", description: "要求音频可用" },
        { flag: "no-audio-playback", type: "boolean", description: "不播放音频" },
        { flag: "audio-dup", type: "boolean", description: "音频复制到主机输出" },
      ],
    },
    {
      id: "recording",
      name: "录制 / Recording",
      options: [
        { flag: "record", alias: "r", type: "string", description: "录制到文件" },
        { flag: "record-format", type: "enum", values: ["mp4", "mkv", "m4a", "mka", "opus", "aac", "flac", "wav"], description: "录制格式" },
        { flag: "record-orientation", type: "string", description: "录制方向" },
        { flag: "time-limit", type: "number", description: "时长限制 (秒)" },
      ],
    },
    {
      id: "control",
      name: "控制 / Control",
      options: [
        { flag: "no-control", type: "boolean", description: "禁用控制" },
        { flag: "keyboard", alias: "K", type: "enum", values: ["auto", "disabled", "sdk", "uhid", "aoa"], description: "键盘注入模式" },
        { flag: "mouse", alias: "M", type: "enum", values: ["auto", "disabled", "sdk", "uhid", "aoa"], description: "鼠标注入模式" },
        { flag: "gamepad", type: "enum", values: ["disabled", "uhid", "aoa"], description: "手柄模式" },
        { flag: "raw-key-events", type: "boolean", description: "原始按键事件" },
        { flag: "prefer-text", type: "boolean", description: "优先文本注入" },
        { flag: "legacy-paste", type: "boolean", description: "旧版粘贴模式" },
        { flag: "show-touches", type: "boolean", description: "显示触摸点" },
        { flag: "no-clipboard-autosync", type: "boolean", description: "禁用剪贴板同步" },
      ],
    },
    {
      id: "display_power",
      name: "屏幕与电源 / Display & Power",
      options: [
        { flag: "turn-screen-off", alias: "S", type: "boolean", description: "关闭设备屏幕" },
        { flag: "stay-awake", alias: "w", type: "boolean", description: "保持唤醒" },
        { flag: "power-on", type: "boolean", description: "启动时点亮屏幕" },
        { flag: "power-off-on-close", type: "boolean", description: "关闭时关机" },
        { flag: "screen-off-timeout", type: "number", description: "熄屏超时" },
        { flag: "keep-active", type: "boolean", description: "保持虚拟显示活跃" },
      ],
    },
    {
      id: "virtual_display",
      name: "虚拟显示 / Virtual display",
      options: [
        { flag: "new-display", type: "string", description: "新建虚拟显示 (WxH[/dpi])" },
        { flag: "start-app", type: "string", description: "启动指定应用" },
        { flag: "no-vd-system-decorations", type: "boolean", description: "无系统装饰" },
        { flag: "no-vd-destroy-content", type: "boolean", description: "关闭不销毁内容" },
        { flag: "display-ime-policy", type: "enum", values: ["local", "fallback", "hide"], description: "IME 策略" },
      ],
    },
    {
      id: "camera",
      name: "摄像头镜像 / Camera",
      options: [
        { flag: "camera-id", type: "string", description: "摄像头 ID" },
        { flag: "camera-size", type: "string", description: "摄像头分辨率" },
        { flag: "camera-facing", type: "enum", values: ["front", "back", "external"], description: "摄像头朝向" },
        { flag: "camera-ar", type: "string", description: "宽高比" },
        { flag: "camera-fps", type: "number", description: "摄像头帧率" },
        { flag: "camera-high-speed", type: "boolean", description: "高速模式" },
        { flag: "camera-torch", type: "boolean", description: "手电筒" },
        { flag: "camera-zoom", type: "number", description: "变焦" },
        { flag: "list-cameras", type: "boolean", description: "列出摄像头" },
        { flag: "list-camera-sizes", type: "boolean", description: "列出摄像头尺寸" },
      ],
    },
    {
      id: "window",
      name: "桌面窗口 / Desktop window (SDL)",
      options: [
        { flag: "no-window", alias: "n", type: "boolean", description: "无窗口 (headless 解码)" },
        { flag: "window-title", type: "string", description: "窗口标题" },
        { flag: "fullscreen", alias: "f", type: "boolean", description: "全屏" },
        { flag: "always-on-top", type: "boolean", description: "置顶" },
        { flag: "window-borderless", type: "boolean", description: "无边框" },
        { flag: "window-x", type: "number", description: "窗口 X" },
        { flag: "window-y", type: "number", description: "窗口 Y" },
        { flag: "window-width", type: "number", description: "窗口宽度" },
        { flag: "window-height", type: "number", description: "窗口高度" },
        { flag: "render-driver", type: "string", description: "渲染驱动" },
        { flag: "render-fit", type: "enum", values: ["auto", "letterbox", "stretched", "unscaled"], description: "缩放模式" },
      ],
    },
    {
      id: "lists",
      name: "查询列表 / List",
      options: [
        { flag: "list-encoders", type: "boolean", description: "列出编码器" },
        { flag: "list-displays", type: "boolean", description: "列出显示器" },
        { flag: "list-apps", type: "boolean", description: "列出应用" },
      ],
    },
    {
      id: "otg",
      name: "OTG / USB",
      options: [{ flag: "otg", type: "boolean", description: "OTG 模式 (无需 adb 调试)" }],
    },
    {
      id: "v4l2",
      name: "V4L2 (Linux)",
      options: [
        { flag: "v4l2-sink", type: "string", description: "输出到 V4L2 设备" },
        { flag: "v4l2-buffer", type: "number", description: "V4L2 缓冲" },
      ],
      platforms: ["linux"],
    },
    {
      id: "cloud_phone",
      name: "Cloud Phone 扩展",
      options: [
        { flag: "cloud-phone-config", type: "string", description: "从配置文件合并参数" },
        { flag: "cloud-phone-capabilities", type: "boolean", description: "输出能力清单 JSON" },
      ],
    },
  ],
  wsScrcpyFeatures: [
    "WebSocket H264 投屏 (MSE/Broadway/TinyH264/WebCodecs)",
    "远程触控与多指",
    "键盘与滚轮",
    "剪贴板同步",
    "文件拖拽推送 APK",
    "adb shell 终端",
    "文件列表/上传/下载",
    "DevTools 调试 WebView",
    "iOS 实验性支持 (ws-qvh / MJPEG)",
  ],
};
